name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.1.3
homepage: https://github.com/lejard-h/angular_recaptcha
author: Hadrien Lejard <hadrien.lejard@gmail.com>
environment:
  sdk: ">=2.0.0-dev.46.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.2
  js: ^0.6.1+1
  dart_browser_loader: ^0.0.6+1
